### Multiple linear regression

In [1]:
# import the relevant libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

In [2]:
# Load the data

data = pd.read_csv('MultipleLR.csv')
data.head()

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83

In [3]:
data.describe()

SAT  Rand 1,2,3        GPA
count    84.000000   84.000000  84.000000
mean   1845.273810    2.059524   3.330238
std     104.530661    0.855192   0.271617
min    1634.000000    1.000000   2.400000
25%    1772.000000    1.000000   3.190000
50%    1846.000000    2.000000   3.380000
75%    1934.000000    3.000000   3.502500
max    2050.000000    3.000000   3.810000

Create the multiple regression

In [4]:
# Declare the dependent and independent variable

x = data[['SAT', 'Rand 1,2,3']]
y = data['GPA']

In [6]:
reg = LinearRegression()
reg.fit(x,y)

LinearRegression()

In [7]:
# Coefficient
reg.coef_

array([ 0.00165354, -0.00826982])

In [8]:
# Intercept
reg.intercept_

0.29603261264909353

Calculating the R-squared

In [9]:
reg.score(x,y)

0.4066811952814282

### Formula for Adjusted R^2
$R^2_{adj.} = 1 - (1-R^2)*\frac{n-1}{n-p-1}$

In [10]:
x.shape

(84, 2)

In [11]:
# n= 84 (number of observactions)
# p= 2 (the number of predictors)
r2  = reg.score(x,y)
n = x.shape[0]
p = x.shape[1]
# calculating the adjusted R-squared
adjusted_r2 = 1-(1-r2)*(n-1)/(n-p-1)
adjusted_r2

0.39203134825134

## Feature Selection

In [12]:
from sklearn.feature_selection import f_regression

In [16]:
f_regression(x,y)
# output=> (arra(F-Stat), array(p-values)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [14]:
p_values = f_regression(x,y)[1]
p_values

array([7.19951844e-11, 6.76291372e-01])

In [15]:
p_values.round(3)

array([0.   , 0.676])

In [ ]:
# from the found f_regression we found the the p_value of Rand 1,2,3 is > 0.05 that means we can disregard that predictor

### Creating the summary table

In [18]:
reg_summary = pd.DataFrame(data= x.columns.values, columns=['Features'])
reg_summary

Features
0         SAT
1  Rand 1,2,3

In [20]:
reg_summary ['Coefficient'] = reg.coef_
reg_summary ['p=values'] = p_values.round(3)

In [21]:
reg_summary

Features  Coefficient  p=values
0         SAT     0.001654     0.000
1  Rand 1,2,3    -0.008270     0.676

In [22]:
# Again through the summary we establish that Rand 1,2,3 is insignificant and useless in this model whereas the SAT is useful