In [1]:
# import the relevant libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

In [2]:
data = pd.read_csv('MultipleLR.csv')
x = data[['SAT', 'Rand 1,2,3']]
y = data['GPA']

### Standardization

In [4]:
from sklearn.preprocessing import StandardScaler

In [5]:
# creating and empty StandardScaler object
scaler = StandardScaler()

In [6]:
# Scaling mechanism
scaler.fit(x)

StandardScaler()

In [8]:
# transforming the x values 
x_scaled = scaler.transform(x)

In [9]:
x_scaled

array([[-1.26338288, -1.24637147],
       [-1.74458431,  1.10632974],
       [-0.82067757,  1.10632974],
       [-1.54247971,  1.10632974],
       [-1.46548748, -0.07002087],
       [-1.68684014, -1.24637147],
       [-0.78218146, -0.07002087],
       [-0.78218146, -1.24637147],
       [-0.51270866, -0.07002087],
       [ 0.04548499,  1.10632974],
       [-1.06127829,  1.10632974],
       [-0.67631715, -0.07002087],
       [-1.06127829, -1.24637147],
       [-1.28263094,  1.10632974],
       [-0.6955652 , -0.07002087],
       [ 0.25721362, -0.07002087],
       [-0.86879772,  1.10632974],
       [-1.64834403, -0.07002087],
       [-0.03150724,  1.10632974],
       [-0.57045283,  1.10632974],
       [-0.81105355,  1.10632974],
       [-1.18639066,  1.10632974],
       [-1.75420834,  1.10632974],
       [-1.52323165, -1.24637147],
       [ 1.23886453, -1.24637147],
       [-0.18549169, -1.24637147],
       [-0.5608288 , -1.24637147],
       [-0.23361183,  1.10632974],
       [ 1.68156984,

### Regression with scaled features

In [10]:
reg = LinearRegression()
reg.fit(x_scaled, y)

LinearRegression()

In [11]:
reg.coef_

array([ 0.17181389, -0.00703007])

In [12]:
reg.intercept_

3.330238095238095

### Creating the summary table

In [15]:
# the ML word for intercept is bias and Weights is the coefficient of features(independent variables)
reg_summary = pd.DataFrame(data=[['Bias'], ['SAT'],['Rand 1,2,3']], columns = ['Features'])
reg_summary ['Weights'] = reg.intercept_, reg.coef_[0], reg.coef_[1]
                           

In [17]:
reg_summary
# The closer a weight is to 0. the smaller its impact
# The bigger the weight, the bigger it's impact

Features   Weights
0        Bias  3.330238
1         SAT  0.171814
2  Rand 1,2,3 -0.007030

In [19]:
# If we select the features through Standardization we can again see that the Rand 1,2,3 holds the weight in negative 
# which is again insignificant for our model

### Making predictions with the standardized coefficients (weights)

In [22]:
# The new data frame shold be arranged in the same way and also must be standardized in the same way

new_data = pd.DataFrame(data=[[1700,2], [1800,1]], columns=['SAT', 'Rand 1,2,3'])
new_data

SAT  Rand 1,2,3
0  1700           2
1  1800           1

In [23]:
new_data_scaled = scaler.transform(new_data)
new_data_scaled

array([[-1.39811928, -0.07002087],
       [-0.43571643, -1.24637147]])

In [24]:
reg.predict(new_data_scaled)

array([3.09051403, 3.26413803])

In [26]:
## Even if we remove the Rand 1,2,3 there will be none to zero changes in the predictions as it holds very low weight(negative in this case)