## Train Test Split

In [1]:
import numpy as np
from sklearn.model_selection import train_test_split

In [3]:
# Generate some data we are going to split
a = np.arange(1,101)
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [30]:
b = np.arange(501,601)
b

array([501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513,
       514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526,
       527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539,
       540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552,
       553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565,
       566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578,
       579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591,
       592, 593, 594, 595, 596, 597, 598, 599, 600])

### Split the data

In [5]:
train_test_split(a)

[array([ 21,  24,  59,   4,  58,  65,  19,  72,  60,   7,  32,  26,  73,
         34,  95,  93,  53,  37,  10, 100,  17,  99,  80,  12,  44,   5,
         84,  33,  51,  83,  76,  30,  41,  64,  28,  11,  31,  69,  91,
         47,  88,  56,  48,  97,  54,  42,  35,  13,  81,   3,  77,  50,
         61,  45,   2,   1,  55,  87,  36,  16,  22,  29,  79,  98,  82,
         52,  43,   6,  75,  94,  49,  25,  71,  18,  46]),
 array([23, 96, 70, 78, 39, 92, 20, 38, 66, 90, 85, 68, 89, 40, 14, 27, 57,
         9, 62, 74, 63, 86, 67,  8, 15])]

In [23]:
# by default it gives us 75,25 for train and test
# but we need 80, 20 for that we define test_size=0.2
# default shuffle=True but if we don't want the data to be Shuffled we use shuffle=False
# to get the shuffle state as we want it to we define random_state


a_train, a_test = train_test_split(a, test_size=0.2, random_state=42)

### Explore the result

In [24]:
a_train.shape, a_test.shape

((80,), (20,))

In [27]:
a_train

array([ 56,  89,  27,  43,  70,  16,  41,  97,  10,  73,  12,  48,  86,
        29,  94,   6,  67,  66,  36,  17,  50,  35,   8,  96,  28,  20,
        82,  26,  63,  14,  25,   4,  18,  39,   9,  79,   7,  65,  37,
        90,  57, 100,  55,  44,  51,  68,  47,  69,  62,  98,  80,  42,
        59,  49,  99,  58,  76,  33,  95,  60,  64,  85,  38,  30,   2,
        53,  22,   3,  24,  88,  92,  75,  87,  83,  21,  61,  72,  15,
        93,  52])

In [28]:
a_test

array([84, 54, 71, 46, 45, 40, 23, 81, 11,  1, 19, 31, 74, 34, 91,  5, 77,
       78, 13, 32])

In [31]:
# We can also use more than one matrix or arrays
a_train, a_test, b_train, b_test = train_test_split(a,b, test_size=0.2, random_state=42)

In [32]:
b_train.shape, b_test.shape

((80,), (20,))

In [33]:
b_train

array([556, 589, 527, 543, 570, 516, 541, 597, 510, 573, 512, 548, 586,
       529, 594, 506, 567, 566, 536, 517, 550, 535, 508, 596, 528, 520,
       582, 526, 563, 514, 525, 504, 518, 539, 509, 579, 507, 565, 537,
       590, 557, 600, 555, 544, 551, 568, 547, 569, 562, 598, 580, 542,
       559, 549, 599, 558, 576, 533, 595, 560, 564, 585, 538, 530, 502,
       553, 522, 503, 524, 588, 592, 575, 587, 583, 521, 561, 572, 515,
       593, 552])

In [34]:
b_test

array([584, 554, 571, 546, 545, 540, 523, 581, 511, 501, 519, 531, 574,
       534, 591, 505, 577, 578, 513, 532])